version: '3'
services:

  flask:
    container_name: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
#    ports:
#      - 80:80
#      - 3031:3031
    restart: always
    tty: true
    volumes:
    - ./flask:/usr/src/app
    environment:
      TZ: Asia/Tokyo


  web:
    container_name: web-server
    hostname: web-server
    build: ./web
    volumes:
      - "./web/nginx.conf:/etc/nginx/nginx.conf"
      - "./tmp/nginx_log:/var/log/nginx"
    ports:
      - "5000:80"
    environment:
      TZ: Asia/Tokyo
    links:
      - flask
